export const svgColors = {
  Bling: "hsla(122, 35%, 55%, 1)",
  Copper: "url(#copper-vertical)",
  Gold: "url(#gold-vertical)",
  // Silver: "url(#silver-vertical)",
  Bronze: "url(#bronze-vertical)",
  RoseGold: "url(#pink-vertical)",
  Gunmetal: "url(#gunmetal-vertical)",
  Crodium: "url(#crodium-vertical)",
  Corundum: "url(#corundum-vertical)",
  Duraplast: "url(#duraplast-vertical)",
  BlackDuraplast: "url(#black-duraplast-vertical)",
  Durasteel: "url(#durasteel-vertical)",
  LaminaSteel: "url(#lamina-steel-vertical)",
  Dolovite: "url(#dolovite-vertical)",
  RoyalChromium: "url(#royal-chromium-vertical)",
  ElectrumPlated: "url(#electrum-plated-vertical)",
  Duralium: "url(#duralium-vertical)",
  Arcetron: "url(#arcetron-vertical)",
  Matte: "url(#matte-vertical)",
  WroshyrWood: "url(#wroshyr-horizontal)",

  // Wood: "url(#Wood)",
  default: "#706F6F",
};
